# Generated by Django 4.2.20 on 2025-04-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SWEB App', max_length=100)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('map_tile_url', models.URLField(blank=True, null=True)),
                ('max_sensor_lines', models.PositiveIntegerField(default=10)),
                ('oauth2_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth2_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth2_redirect_uri', models.URLField(blank=True, null=True)),
                ('oauth2_authorization_url', models.URLField(blank=True, null=True)),
                ('oauth2_token_url', models.URLField(blank=True, null=True)),
                ('oauth2_scope', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
