# Generated by Django 4.2.20 on 2025-05-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skudra', '0006_remove_receiver_created_by_and_more'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvoyConfigLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('VALIDATED', 'Validated')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('config_snapshot', models.JSONField(blank=True, null=True)),
                ('triggered_by_sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envoy_logs', to='skudra.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
