# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from skudra.GrpcProtos import advanced_mode_grpc_pb2 as advanced__mode__grpc__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from skudra.GrpcProtos import shared_architecture_pb2 as shared__architecture__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in advanced_mode_grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdvancedModeGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AdvancedModeHandshake = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/AdvancedModeHandshake',
                request_serializer=advanced__mode__grpc__pb2.AdvancedModeHandshakeRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.AdvancedModeHandshakeReply.FromString,
                _registered_method=True)
        self.ReplyConnectReceiver = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/ReplyConnectReceiver',
                request_serializer=advanced__mode__grpc__pb2.ConnectReceiverRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.ConnectReceiverReply.FromString,
                _registered_method=True)
        self.StreamMeasurements = channel.unary_stream(
                '/advanced_mode_grpc.AdvancedModeGrpc/StreamMeasurements',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=shared__architecture__pb2.MeasurementStreamDataGrpc.FromString,
                _registered_method=True)
        self.ReplyEnableLivestreaming = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/ReplyEnableLivestreaming',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ReplyDisableLivestreaming = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/ReplyDisableLivestreaming',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestAllSettings = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestAllSettings',
                request_serializer=advanced__mode__grpc__pb2.AllSettingsRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.AllSettingsReply.FromString,
                _registered_method=True)
        self.RequestToChangeReceiverSetting = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestToChangeReceiverSetting',
                request_serializer=advanced__mode__grpc__pb2.ChangeReceiverSettingRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.AllSettingsReply.FromString,
                _registered_method=True)
        self.RequestAntennaList = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestAntennaList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.AntennaListReply.FromString,
                _registered_method=True)
        self.RequestChangeAntenna = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestChangeAntenna',
                request_serializer=advanced__mode__grpc__pb2.SwitchAntennaRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.AntennaListReply.FromString,
                _registered_method=True)
        self.RequestMeasuringPresetList = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestMeasuringPresetList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.MeasuringPresetListReply.FromString,
                _registered_method=True)
        self.RequestChangeDeviceMode = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestChangeDeviceMode',
                request_serializer=advanced__mode__grpc__pb2.ChangeDeviceModeRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.ChangeDeviceModeReply.FromString,
                _registered_method=True)
        self.RequestScpiExecution = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestScpiExecution',
                request_serializer=advanced__mode__grpc__pb2.ScpiExecutionRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.ScpiExecutionReply.FromString,
                _registered_method=True)
        self.RequestStartScheduledMeasuring = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestStartScheduledMeasuring',
                request_serializer=advanced__mode__grpc__pb2.StartScheduledMeasuringRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestStartDirectMeasuring = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestStartDirectMeasuring',
                request_serializer=advanced__mode__grpc__pb2.StartDirectMeasuringRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestStopMeasuring = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestStopMeasuring',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.StopMeasuringReply.FromString,
                _registered_method=True)
        self.RequestPresetDevice = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestPresetDevice',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestRotatorAlignment = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestRotatorAlignment',
                request_serializer=advanced__mode__grpc__pb2.RotatorAlignmentRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.RotatorAlignmentReply.FromString,
                _registered_method=True)
        self.RequestRotatorStop = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestRotatorStop',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestStoreMeasuringPreset = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestStoreMeasuringPreset',
                request_serializer=advanced__mode__grpc__pb2.StoreMeasuringPresetRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.MeasuringPresetListReply.FromString,
                _registered_method=True)
        self.RequestDeleteMeasuringPreset = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestDeleteMeasuringPreset',
                request_serializer=advanced__mode__grpc__pb2.DeleteMeasuringPresetRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestUpdateMeasuringPreset = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestUpdateMeasuringPreset',
                request_serializer=advanced__mode__grpc__pb2.UpdateMeasuringPresetRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.MeasuringPresetListReply.FromString,
                _registered_method=True)
        self.RequestRemoteMode = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestRemoteMode',
                request_serializer=advanced__mode__grpc__pb2.RemoteModeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestApplyMeasuringPreset = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestApplyMeasuringPreset',
                request_serializer=advanced__mode__grpc__pb2.ApplyMeasuringPresetRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.ApplyMeasuringPresetReply.FromString,
                _registered_method=True)
        self.RequestRecording = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestRecording',
                request_serializer=advanced__mode__grpc__pb2.RecordingRequest.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.RecordingReply.FromString,
                _registered_method=True)
        self.RequestDisconnect = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestDisconnect',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestCurrentAlignment = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestCurrentAlignment',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=advanced__mode__grpc__pb2.RotatorAlignmentReply.FromString,
                _registered_method=True)
        self.RequestNewSimpleModePresetCreation = channel.unary_unary(
                '/advanced_mode_grpc.AdvancedModeGrpc/RequestNewSimpleModePresetCreation',
                request_serializer=advanced__mode__grpc__pb2.NewSimpleModePresetCreationRequestGrpc.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class AdvancedModeGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AdvancedModeHandshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyConnectReceiver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMeasurements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyEnableLivestreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyDisableLivestreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAllSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestToChangeReceiverSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAntennaList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestChangeAntenna(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestMeasuringPresetList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestChangeDeviceMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestScpiExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestStartScheduledMeasuring(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestStartDirectMeasuring(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestStopMeasuring(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPresetDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRotatorAlignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRotatorStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestStoreMeasuringPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestDeleteMeasuringPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestUpdateMeasuringPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRemoteMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestApplyMeasuringPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestDisconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCurrentAlignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestNewSimpleModePresetCreation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdvancedModeGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AdvancedModeHandshake': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvancedModeHandshake,
                    request_deserializer=advanced__mode__grpc__pb2.AdvancedModeHandshakeRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.AdvancedModeHandshakeReply.SerializeToString,
            ),
            'ReplyConnectReceiver': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplyConnectReceiver,
                    request_deserializer=advanced__mode__grpc__pb2.ConnectReceiverRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.ConnectReceiverReply.SerializeToString,
            ),
            'StreamMeasurements': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMeasurements,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=shared__architecture__pb2.MeasurementStreamDataGrpc.SerializeToString,
            ),
            'ReplyEnableLivestreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplyEnableLivestreaming,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ReplyDisableLivestreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplyDisableLivestreaming,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestAllSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAllSettings,
                    request_deserializer=advanced__mode__grpc__pb2.AllSettingsRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.AllSettingsReply.SerializeToString,
            ),
            'RequestToChangeReceiverSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestToChangeReceiverSetting,
                    request_deserializer=advanced__mode__grpc__pb2.ChangeReceiverSettingRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.AllSettingsReply.SerializeToString,
            ),
            'RequestAntennaList': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAntennaList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=advanced__mode__grpc__pb2.AntennaListReply.SerializeToString,
            ),
            'RequestChangeAntenna': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestChangeAntenna,
                    request_deserializer=advanced__mode__grpc__pb2.SwitchAntennaRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.AntennaListReply.SerializeToString,
            ),
            'RequestMeasuringPresetList': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestMeasuringPresetList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=advanced__mode__grpc__pb2.MeasuringPresetListReply.SerializeToString,
            ),
            'RequestChangeDeviceMode': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestChangeDeviceMode,
                    request_deserializer=advanced__mode__grpc__pb2.ChangeDeviceModeRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.ChangeDeviceModeReply.SerializeToString,
            ),
            'RequestScpiExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestScpiExecution,
                    request_deserializer=advanced__mode__grpc__pb2.ScpiExecutionRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.ScpiExecutionReply.SerializeToString,
            ),
            'RequestStartScheduledMeasuring': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestStartScheduledMeasuring,
                    request_deserializer=advanced__mode__grpc__pb2.StartScheduledMeasuringRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestStartDirectMeasuring': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestStartDirectMeasuring,
                    request_deserializer=advanced__mode__grpc__pb2.StartDirectMeasuringRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestStopMeasuring': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestStopMeasuring,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=advanced__mode__grpc__pb2.StopMeasuringReply.SerializeToString,
            ),
            'RequestPresetDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPresetDevice,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestRotatorAlignment': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRotatorAlignment,
                    request_deserializer=advanced__mode__grpc__pb2.RotatorAlignmentRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.RotatorAlignmentReply.SerializeToString,
            ),
            'RequestRotatorStop': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRotatorStop,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestStoreMeasuringPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestStoreMeasuringPreset,
                    request_deserializer=advanced__mode__grpc__pb2.StoreMeasuringPresetRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.MeasuringPresetListReply.SerializeToString,
            ),
            'RequestDeleteMeasuringPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestDeleteMeasuringPreset,
                    request_deserializer=advanced__mode__grpc__pb2.DeleteMeasuringPresetRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestUpdateMeasuringPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestUpdateMeasuringPreset,
                    request_deserializer=advanced__mode__grpc__pb2.UpdateMeasuringPresetRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.MeasuringPresetListReply.SerializeToString,
            ),
            'RequestRemoteMode': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRemoteMode,
                    request_deserializer=advanced__mode__grpc__pb2.RemoteModeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestApplyMeasuringPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestApplyMeasuringPreset,
                    request_deserializer=advanced__mode__grpc__pb2.ApplyMeasuringPresetRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.ApplyMeasuringPresetReply.SerializeToString,
            ),
            'RequestRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRecording,
                    request_deserializer=advanced__mode__grpc__pb2.RecordingRequest.FromString,
                    response_serializer=advanced__mode__grpc__pb2.RecordingReply.SerializeToString,
            ),
            'RequestDisconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestDisconnect,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestCurrentAlignment': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCurrentAlignment,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=advanced__mode__grpc__pb2.RotatorAlignmentReply.SerializeToString,
            ),
            'RequestNewSimpleModePresetCreation': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestNewSimpleModePresetCreation,
                    request_deserializer=advanced__mode__grpc__pb2.NewSimpleModePresetCreationRequestGrpc.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'advanced_mode_grpc.AdvancedModeGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('advanced_mode_grpc.AdvancedModeGrpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdvancedModeGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AdvancedModeHandshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/AdvancedModeHandshake',
            advanced__mode__grpc__pb2.AdvancedModeHandshakeRequest.SerializeToString,
            advanced__mode__grpc__pb2.AdvancedModeHandshakeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplyConnectReceiver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/ReplyConnectReceiver',
            advanced__mode__grpc__pb2.ConnectReceiverRequest.SerializeToString,
            advanced__mode__grpc__pb2.ConnectReceiverReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMeasurements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/StreamMeasurements',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            shared__architecture__pb2.MeasurementStreamDataGrpc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplyEnableLivestreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/ReplyEnableLivestreaming',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplyDisableLivestreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/ReplyDisableLivestreaming',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestAllSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestAllSettings',
            advanced__mode__grpc__pb2.AllSettingsRequest.SerializeToString,
            advanced__mode__grpc__pb2.AllSettingsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestToChangeReceiverSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestToChangeReceiverSetting',
            advanced__mode__grpc__pb2.ChangeReceiverSettingRequest.SerializeToString,
            advanced__mode__grpc__pb2.AllSettingsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestAntennaList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestAntennaList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            advanced__mode__grpc__pb2.AntennaListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestChangeAntenna(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestChangeAntenna',
            advanced__mode__grpc__pb2.SwitchAntennaRequest.SerializeToString,
            advanced__mode__grpc__pb2.AntennaListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestMeasuringPresetList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestMeasuringPresetList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            advanced__mode__grpc__pb2.MeasuringPresetListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestChangeDeviceMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestChangeDeviceMode',
            advanced__mode__grpc__pb2.ChangeDeviceModeRequest.SerializeToString,
            advanced__mode__grpc__pb2.ChangeDeviceModeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestScpiExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestScpiExecution',
            advanced__mode__grpc__pb2.ScpiExecutionRequest.SerializeToString,
            advanced__mode__grpc__pb2.ScpiExecutionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestStartScheduledMeasuring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestStartScheduledMeasuring',
            advanced__mode__grpc__pb2.StartScheduledMeasuringRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestStartDirectMeasuring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestStartDirectMeasuring',
            advanced__mode__grpc__pb2.StartDirectMeasuringRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestStopMeasuring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestStopMeasuring',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            advanced__mode__grpc__pb2.StopMeasuringReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPresetDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestPresetDevice',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestRotatorAlignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestRotatorAlignment',
            advanced__mode__grpc__pb2.RotatorAlignmentRequest.SerializeToString,
            advanced__mode__grpc__pb2.RotatorAlignmentReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestRotatorStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestRotatorStop',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestStoreMeasuringPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestStoreMeasuringPreset',
            advanced__mode__grpc__pb2.StoreMeasuringPresetRequest.SerializeToString,
            advanced__mode__grpc__pb2.MeasuringPresetListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestDeleteMeasuringPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestDeleteMeasuringPreset',
            advanced__mode__grpc__pb2.DeleteMeasuringPresetRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestUpdateMeasuringPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestUpdateMeasuringPreset',
            advanced__mode__grpc__pb2.UpdateMeasuringPresetRequest.SerializeToString,
            advanced__mode__grpc__pb2.MeasuringPresetListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestRemoteMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestRemoteMode',
            advanced__mode__grpc__pb2.RemoteModeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestApplyMeasuringPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestApplyMeasuringPreset',
            advanced__mode__grpc__pb2.ApplyMeasuringPresetRequest.SerializeToString,
            advanced__mode__grpc__pb2.ApplyMeasuringPresetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestRecording',
            advanced__mode__grpc__pb2.RecordingRequest.SerializeToString,
            advanced__mode__grpc__pb2.RecordingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestDisconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestDisconnect',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestCurrentAlignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestCurrentAlignment',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            advanced__mode__grpc__pb2.RotatorAlignmentReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestNewSimpleModePresetCreation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/advanced_mode_grpc.AdvancedModeGrpc/RequestNewSimpleModePresetCreation',
            advanced__mode__grpc__pb2.NewSimpleModePresetCreationRequestGrpc.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
