# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: welcome.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'welcome.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from skudra.GrpcProtos import decimal_value_pb2 as decimal__value__pb2
from skudra.GrpcProtos import shared_architecture_pb2 as shared__architecture__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwelcome.proto\x12\x0cwelcome_grpc\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13\x64\x65\x63imal_value.proto\x1a\x19shared_architecture.proto\"H\n\x10ReceiverListGrpc\x12\x34\n\treceivers\x18\x02 \x03(\x0b\x32!.shared_architecture.ReceiverInfo\"\x8d\x01\n\x10HandshakeRequest\x12.\n\x08username\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0cserver_token\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x15\n\ris_guest_user\x18\x03 \x01(\x08\"\xdd\x02\n\x0eHandshakeReply\x12\x34\n\treceivers\x18\x01 \x03(\x0b\x32!.shared_architecture.ReceiverInfo\x12.\n\tlongitude\x18\x02 \x01(\x0b\x32\x1b.decimal_value.DecimalValue\x12-\n\x08latitude\x18\x03 \x01(\x0b\x32\x1b.decimal_value.DecimalValue\x12\x17\n\x0fuser_has_access\x18\x04 \x01(\x08\x12\x13\n\x0b\x64river_name\x18\x05 \x01(\t\x12\x34\n\x0e\x66rontend_token\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12R\n\x14\x61nalysis_credentials\x18\x07 \x01(\x0b\x32\x34.shared_architecture.SerializableDatabaseCredentials2\xa8\x01\n\x0bWelcomeGrpc\x12I\n\tHandshake\x12\x1e.welcome_grpc.HandshakeRequest\x1a\x1c.welcome_grpc.HandshakeReply\x12N\n\x12StreamReceiverList\x12\x16.google.protobuf.Empty\x1a\x1e.welcome_grpc.ReceiverListGrpc0\x01\x42\x13\xaa\x02\x10VASES.GrpcProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'welcome_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020VASES.GrpcProtos'
  _globals['_RECEIVERLISTGRPC']._serialized_start=140
  _globals['_RECEIVERLISTGRPC']._serialized_end=212
  _globals['_HANDSHAKEREQUEST']._serialized_start=215
  _globals['_HANDSHAKEREQUEST']._serialized_end=356
  _globals['_HANDSHAKEREPLY']._serialized_start=359
  _globals['_HANDSHAKEREPLY']._serialized_end=708
  _globals['_WELCOMEGRPC']._serialized_start=711
  _globals['_WELCOMEGRPC']._serialized_end=879
# @@protoc_insertion_point(module_scope)
