version: "3.9"
services:
  backend:
    build: ./backend
    container_name: sweb_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: sweb.settings
    # For local dev, you might mount code if you want hot reload
    # volumes:
    #   - ./backend:/app

  frontend:
    build: ./frontend
    container_name: sweb_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    # For local dev, you might mount code if you want hot reload
    # volumes:
    #   - ./frontend:/app

  db:
    image: postgres:15
    container_name: sweb_db
    environment:
      POSTGRES_DB: swebdb
      POSTGRES_USER: swebuser
      POSTGRES_PASSWORD: swebpass
    ports:
      - "5432:5432"
