# Generated by Django 4.2.20 on 2025-04-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skudra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='token',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SensorUptimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_logs', to='skudra.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
