# Generated by Django 4.2.20 on 2025-04-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skudra', '0002_sensor_token_sensoruptimelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='analysis_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
