# Generated by Django 4.2.20 on 2025-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skudra', '0003_sensor_analysis_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
