# Generated by Django 4.2.20 on 2025-04-07 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skudra', '0004_alter_sensor_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_state_ready',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
