# Generated by Django 4.2.20 on 2025-04-10 10:30

from django.db import migrations, models
import uuid
# from .models import Sensor, Receiver


def generate_uuids(apps, schema_editor):
    Receiver = apps.get_model('skudra', 'Receiver')
    for row in Receiver.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=['guid'])

class Migration(migrations.Migration):

    dependencies = [
        ('skudra', '0005_sensor_last_state_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='updated_by',
        ),
        migrations.RunPython(generate_uuids),
        migrations.AddField(
            model_name='receiver',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
