/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/map/': RouteRecordInfo<'/map/', '/map', Record<never, never>, Record<never, never>>,
    '/measurements/': RouteRecordInfo<'/measurements/', '/measurements', Record<never, never>, Record<never, never>>,
    '/measurements/ReceiverStream': RouteRecordInfo<'/measurements/ReceiverStream', '/measurements/ReceiverStream', Record<never, never>, Record<never, never>>,
    '/measurements/simpleModeForm': RouteRecordInfo<'/measurements/simpleModeForm', '/measurements/simpleModeForm', Record<never, never>, Record<never, never>>,
    '/measurements/test': RouteRecordInfo<'/measurements/test', '/measurements/test', Record<never, never>, Record<never, never>>,
    '/NotFoundPage': RouteRecordInfo<'/NotFoundPage', '/NotFoundPage', Record<never, never>, Record<never, never>>,
  }
}
